sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 20
before_install:
  - npm install -g npm
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run build
  # - npm run coverage
  # - npm run report-coverage
after_success:
  - npx semantic-release
