dist: focal

language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 20.16.0

stages:
  - release
  
jobs:
  include:
    - stage: "release"
      before_script: 
      - npm ci
      - npm test
      script: npx semantic-release
