# Specify the distribution
dist: jammy

# Use Node.js as the language
language: node_js
node_js:
  - '20.16.0'

# Cache dependencies to speed up builds
cache:
  directories:
    - node_modules

# Define stages
stages:
  - name: install
  - name: test
  - name: coverage
  - name: deploy

# Notifications
notifications:
  email: false
  #   on_success: always
  #   on_failure: always

# Specify the branches that should trigger builds
branches:
  only:
    - main
    - develop
    - v*

# Install dependencies, run tests, and perform build steps
jobs:
  include:
    # Job to install dependencies
    - name: Install Dependencies
      stage: install
      script:
        - npm ci
    
    # Job to run tests
    - name: Run Tests
      stage: test
      script:
        - npm test

    # Job to check code coverage
    - name: Check Coverage
      stage: coverage
      script:
        - mkdir -p .nyc_output # Ensure the directory is created
        - npm run check-coverage
    
    # Job to report code coverage
    - name: Report Coverage
      stage: coverage
      script:
        - npm run report-coverage

# Deployment setup
deploy:
  provider: script
  script:
    - npx semantic-release
  on:
    branch:
      - main
      - v*