dist: focal

language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 20.16.0

stages:
  - test
  - release
  
jobs:
  include:
    - stage: "test"
      before_script: npm ci
      script: npm test
    - stage: release
      before_script: npm ci
      script:
        - echo "Executing release script..."
        - npx semantic-release
      before_deploy:
        - echo "Before deploy step..."
        - echo "GH_TOKEN: $GH_TOKEN"
        - echo "NPM_TOKEN: $NPM_TOKEN"
      after_deploy:
        - echo "After deploy step..."
