sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node  # This will use the latest stable Node.js version
before_install:
  - npm install -g npm
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npx semantic-release
env:
  global:
    - GH_TOKEN=${GH_TOKEN}
    - NPM_TOKEN=${NPM_TOKEN}
