sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 20
before_install:
  - npm install -g npm@latest  # Ensure you're installing the latest npm
install:
  - npm ci  # Use npm ci for cleaner and faster installs
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release